up

diff --git a/.github/workflows/python-poetry-ci.yml b/.github/workflows/python-poetry-ci.yml
--- a/.github/workflows/python-poetry-ci.yml
+++ b/.github/workflows/python-poetry-ci.yml
@@ -42,116 +42,117 @@ jobs:
           pipx-tools: '["poetry"]'
           poetry-dependency-groups: '["main", "dev"]'
         
-  tests:
-    name: Tests
-    runs-on: ${{ inputs.os }}
-    needs: setup-environment
+  # tests:
+  #   name: Tests
+  #   runs-on: ${{ inputs.os }}
+  #   needs: setup-environment
     
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v4
 
-      - name: Setup Environment
-        uses: ./.github/actions/python/setup-python-pipx-poetry
-        with:
-          pipx-tools: '["poetry"]'
-          poetry-dependency-groups: '["main", "dev"]'
+  #     - name: Setup Environment
+  #       uses: ./.github/actions/python/setup-python-pipx-poetry
+  #       with:
+  #         pipx-tools: '["poetry"]'
+  #         poetry-dependency-groups: '["main", "dev"]'
 
-      - name: Run Unit Tests
-        uses: ./.github/actions/python/poetry/pytest
-        with:
-          test-path: tests/unit/
-          run-in-parallel: true
-          additional-pytest-options: --tb=short
+  #     - name: Run Unit Tests
+  #       uses: ./.github/actions/python/poetry/pytest
+  #       with:
+  #         test-path: tests/unit/
+  #         run-in-parallel: true
+  #         additional-pytest-options: --tb=short
 
-      - name: Run Integration Tests
-        uses: ./.github/actions/python/poetry/pytest
-        with:
-          test-path: tests/integration/
-          run-in-parallel: true
-          additional-pytest-options: --tb=short
+  #     - name: Run Integration Tests
+  #       uses: ./.github/actions/python/poetry/pytest
+  #       with:
+  #         test-path: tests/integration/
+  #         run-in-parallel: true
+  #         additional-pytest-options: --tb=short
 
-      - name: Run Code Coverage
-        id: code-coverage
-        uses: ./.github/actions/python/poetry/pytest-code-coverage
-        with:
-          test-path: tests/
-          coverage-report-format: xml
-          coverage-artifact-name: coverage-report-${{ inputs.poetry-package-name }}
-          coverage-artifact-path: coverage.xml
-          upload-to-codecov: false
-          run-in-parallel: true
+  #     - name: Run Code Coverage
+  #       id: code-coverage
+  #       uses: ./.github/actions/python/poetry/pytest-code-coverage
+  #       with:
+  #         test-path: tests/
+  #         coverage-report-format: xml
+  #         coverage-artifact-name: coverage-report-${{ inputs.poetry-package-name }}
+  #         coverage-artifact-path: coverage.xml
+  #         upload-to-codecov: false
+  #         run-in-parallel: true
 
-      - name: Code Coverage Guard
-        uses: ./.github/actions/python/code-quality/coverage-guard
-        with:
-          threshold: 95
-          artifact-name: ${{ steps.code-coverage.outputs.coverage-artifact-name }}
-          artifact-path: ${{ steps.code-coverage.outputs.coverage-artifact-path }}
+  #     - name: Code Coverage Guard
+  #       uses: ./.github/actions/python/code-quality/coverage-guard
+  #       with:
+  #         threshold: 95
+  #         artifact-name: ${{ steps.code-coverage.outputs.coverage-artifact-name }}
+  #         artifact-path: ${{ steps.code-coverage.outputs.coverage-artifact-path }}
 
-  code-quality:
-    name: Code Quality
-    runs-on: ${{ inputs.os }}
-    needs: [setup-environment, tests]
+  # code-quality:
+  #   name: Code Quality
+  #   runs-on: ${{ inputs.os }}
+  #   needs: [setup-environment, tests]
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v4
 
-      - name: Setup Environment
-        uses: ./.github/actions/python/setup-python-pipx-poetry
-        with:
-          pipx-tools: '["poetry"]'
-          poetry-dependency-groups: '["main", "dev"]'
+  #     - name: Setup Environment
+  #       uses: ./.github/actions/python/setup-python-pipx-poetry
+  #       with:
+  #         pipx-tools: '["poetry"]'
+  #         poetry-dependency-groups: '["main", "dev"]'
 
-      - name: Check Linting
-        id: linting
-        continue-on-error: true
-        uses: ./.github/actions/python/code-quality/flake8
-        with:
-          paths: ${{ inputs.poetry-package-name }}/ tests/
+  #     - name: Check Linting
+  #       id: linting
+  #       continue-on-error: true
+  #       uses: ./.github/actions/python/code-quality/flake8
+  #       with:
+  #         paths: ${{ inputs.poetry-package-name }}/ tests/
 
-      - name: Check Code Formatting
-        id: formatting
-        continue-on-error: true
-        uses: ./.github/actions/python/code-quality/black
-        with:
-          paths: ${{ inputs.poetry-package-name }}/ tests/
+  #     - name: Check Code Formatting
+  #       id: formatting
+  #       continue-on-error: true
+  #       uses: ./.github/actions/python/code-quality/black
+  #       with:
+  #         paths: ${{ inputs.poetry-package-name }}/ tests/
 
-      - name: Check Import Sorting
-        id: sorting
-        continue-on-error: true
-        uses: ./.github/actions/python/code-quality/isort
-        with:
-          paths: ${{ inputs.poetry-package-name }}/ tests/
+  #     - name: Check Import Sorting
+  #       id: sorting
+  #       continue-on-error: true
+  #       uses: ./.github/actions/python/code-quality/isort
+  #       with:
+  #         paths: ${{ inputs.poetry-package-name }}/ tests/
 
-      - name: Check All Code Quality Steps
-        if: always()
-        env:
-          CODE_COVERAGE_OUTCOME: ${{ needs.tests.result == 'success' }}
-          LINTING_OUTCOME: ${{ steps.linting.outcome == 'success' }}
-          FORMATTING_OUTCOME: ${{ steps.formatting.outcome == 'success' }}
-          SORTING_OUTCOME: ${{ steps.sorting.outcome == 'success' }}
-        shell: bash
-        run: |
-          # Check if any of the code quality steps failed
-          if [[ "$CODE_COVERAGE_OUTCOME" == "false" ]] || \
-            #  [[ "$LINTING_OUTCOME" == "false" ]] || \
-             [[ "$FORMATTING_OUTCOME" == "false" ]] || \
-             [[ "$SORTING_OUTCOME" == "false" ]]; then
-            echo "❌ One or more checks failed:"
-            echo "  - Code coverage: $CODE_COVERAGE_OUTCOME"
-            echo "  - Linting: $LINTING_OUTCOME"
-            echo "  - Formatting: $FORMATTING_OUTCOME"
-            echo "  - Import sorting: $SORTING_OUTCOME"
-            exit 1
-          else
-            echo "✅ All checks passed!"
-          fi
+  #     - name: Check All Code Quality Steps
+  #       if: always()
+  #       env:
+  #         CODE_COVERAGE_OUTCOME: ${{ needs.tests.result == 'success' }}
+  #         LINTING_OUTCOME: ${{ steps.linting.outcome == 'success' }}
+  #         FORMATTING_OUTCOME: ${{ steps.formatting.outcome == 'success' }}
+  #         SORTING_OUTCOME: ${{ steps.sorting.outcome == 'success' }}
+  #       shell: bash
+  #       run: |
+  #         # Check if any of the code quality steps failed
+  #         if [[ "$CODE_COVERAGE_OUTCOME" == "false" ]] || \
+  #            [[ "$LINTING_OUTCOME" == "false" ]] || \
+  #            [[ "$FORMATTING_OUTCOME" == "false" ]] || \
+  #            [[ "$SORTING_OUTCOME" == "false" ]]; then
+  #           echo "❌ One or more checks failed:"
+  #           echo "  - Code coverage: $CODE_COVERAGE_OUTCOME"
+  #           echo "  - Linting: $LINTING_OUTCOME"
+  #           echo "  - Formatting: $FORMATTING_OUTCOME"
+  #           echo "  - Import sorting: $SORTING_OUTCOME"
+  #           exit 1
+  #         else
+  #           echo "✅ All checks passed!"
+  #         fi
+  
   package:
     name: Package
     runs-on: ${{ inputs.os }}
-    needs: [setup-environment, tests]
+    needs: [setup-environment]
 
     steps:
       - name: Checkout Code
